name: brewsage
version: 0.1.0.0
github: "gerdreiss/brewsage"
license: BSD3
author: "Gerd Reiss"
maintainer: "gerd@reiss.pro"
copyright: "Gerd Reiss 2019"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Dev

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/gerdreiss/brewsage#readme>

dependencies:
  - base >= 4.7 && < 5
  - ansi-terminal
  - brick <= 0.70.1
  - bytestring
  - cursor
  - microlens
  - microlens-th
  - parallel-io
  - split
  - text
  - time
  - typed-process
  - vty <= 5.33

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings
    - TemplateHaskell

executables:
  brewsage-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Werror
      - -Wunused-imports
      - -Wwarn=unused-imports
    default-extensions:
      - OverloadedStrings
    dependencies:
      - brewsage
